package com.embabel.guide.domain

import org.drivine.manager.GraphObjectManager
import org.drivine.query.dsl.*
import org.springframework.beans.factory.annotation.Qualifier
import org.springframework.stereotype.Repository
import org.springframework.transaction.annotation.Transactional
import java.util.Optional

/**
 * GraphView-based implementation of GuideUserRepository.
 * Uses the type-safe DSL generated by Drivine KSP.
 */
@Repository
class GraphObjectGuideUserRepository(
    @Qualifier("neoGraphObjectManager") private val graphObjectManager: GraphObjectManager
) : GuideUserRepository {

    @Transactional(readOnly = true)
    override fun findByDiscordUserId(discordUserId: String): Optional<GuideUser> {
        val results = graphObjectManager.loadAll<GuideUser> {
            where {
                query.discordUserInfo.id eq discordUserId
            }
        }
        return Optional.ofNullable(results.firstOrNull())
    }

    @Transactional(readOnly = true)
    override fun findByWebUserId(webUserId: String): Optional<GuideUser> {
        val results = graphObjectManager.loadAll<GuideUser> {
            where {
                query.webUser.id eq webUserId
            }
        }
        return Optional.ofNullable(results.firstOrNull())
    }

    @Transactional(readOnly = true)
    override fun findAnonymousWebUser(): Optional<GuideUser> {
        // Use AnonymousGuideUser GraphView which only matches users with Anonymous label
        val results = graphObjectManager.loadAll(AnonymousGuideUser::class.java)
        return Optional.ofNullable(results.firstOrNull()?.toGuideUser())
    }

    @Transactional(readOnly = true)
    override fun findByWebUserName(userName: String): Optional<GuideUser> {
        val results = graphObjectManager.loadAll<GuideUser> {
            where {
                query.webUser.userName eq userName
            }
        }
        return Optional.ofNullable(results.firstOrNull())
    }

    @Transactional(readOnly = true)
    override fun findById(id: String): Optional<GuideUser> {
        val results = graphObjectManager.loadAll<GuideUser> {
            where {
                query.core.id eq id
            }
        }
        return Optional.ofNullable(results.firstOrNull())
    }

    @Transactional
    override fun createWithDiscord(
        guideUserData: GuideUserData,
        discordUserInfo: DiscordUserInfoData
    ): GuideUser {
        val guideUser = GuideUser(
            core = guideUserData,
            discordUserInfo = discordUserInfo
        )
        return graphObjectManager.save(guideUser)
    }

    @Transactional
    override fun createWithWebUser(
        guideUserData: GuideUserData,
        webUserData: WebUserData
    ): GuideUser {
        val guideUser = GuideUser(
            core = guideUserData,
            webUser = webUserData
        )
        return graphObjectManager.save(guideUser)
    }

    @Transactional
    override fun save(guideUser: GuideUser): GuideUser {
        return graphObjectManager.save(guideUser)
    }

    @Transactional
    override fun updatePersona(guideUserId: String, persona: String) {
        val guideUser = findById(guideUserId).orElseThrow {
            IllegalArgumentException("GuideUser not found: $guideUserId")
        }
        val updated = guideUser.copy(core = guideUser.core.copy(persona = persona))
        graphObjectManager.save(updated)
    }

    @Transactional
    override fun updateCustomPrompt(guideUserId: String, customPrompt: String) {
        val guideUser = findById(guideUserId).orElseThrow {
            IllegalArgumentException("GuideUser not found: $guideUserId")
        }
        val updated = guideUser.copy(core = guideUser.core.copy(customPrompt = customPrompt))
        graphObjectManager.save(updated)
    }

    @Transactional(readOnly = true)
    override fun findAll(): List<GuideUser> {
        return graphObjectManager.loadAll<GuideUser> { }
    }

    @Transactional
    override fun deleteAll() {
        graphObjectManager.deleteAll<GuideUser> { }
    }

    @Transactional
    override fun deleteByUsernameStartingWith(prefix: String) {
        graphObjectManager.deleteAll<GuideUser> {
            where {
                query.webUser.userName startsWith prefix
            }
        }
    }
}
